version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
    networks:
      - mynetwork

  app:
    build: .
    container_name: rentx
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
    driver: local
